/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package beyzaHw;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

   @Test
   public void testEqual() {
      ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(4, 2, 1, 3));

      assertTrue(App.isItEqualAtX(arr1, arr2, 2));
    }

    @Test
    public void testNotEqual() {
      ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(4, 2, 1, 3));
      assertFalse(App.isItEqualAtX(arr1, arr2, 3));
    }

    @Test
    public void testEmptyArray() {
      ArrayList<Integer> arr1 = new ArrayList<>();
      ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(4, 2, 1, 3));
      assertFalse(App.isItEqualAtX(arr1, arr2, 3));
    }

    @Test
    public void testNull() {
      ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(4, 2, 1, 3));
      assertFalse(App.isItEqualAtX(null, arr2, 1));
    }

    @Test
    public void testxIsOutOfBounds(){
      ArrayList<Integer> arr1 = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
      ArrayList<Integer> arr2 = new ArrayList<>(Arrays.asList(4, 2, 1, 3));
      assertThrows(NullPointerException.class , () -> {App.isItEqualAtX(arr1, arr2, -1);});
    }
}
